### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [ZoidTechnology/PCIce#1]
Hello!

I found this project from https://hackaday.com/2023/04/03/server-network-cards-made-extra-cool/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and design files in any purpose?
It would be great to see any popular open source license.

**Comment by ZoidTechnology** [comment]
That's a great question! I'm not actually sure at this stage, but I'm leaning towards GPLv3. I'll need to do a bit more research into possible licences before picking one. Let me know if there's one you'd suggest!

**Comment by vazhnov** [comment]
My personal choice would be: [MIT license](https://spdx.org/licenses/MIT.html) for a code and [CC-BY 4.0 international](https://creativecommons.org/licenses/by/4.0/) for design files/pictures/documentation.

**Comment by ZoidTechnology** [comment]
Sorry for the delay. I've decided to go ahead with the GPLv3 license. Let me know if you need anything else clarified!

**Comment by vazhnov** [comment]
GPL-3.0 — amazing!
Thank you!
